"""
Ocean acoustic environment definition.

Provides the Environment class for specifying water column properties
(sound speed profiles, bathymetry, boundary conditions) used by all
propagation models. Supports both range-independent and range-dependent
configurations.
"""

import copy as _copy
import numpy as np
from typing import Union, List, Tuple, Optional
from dataclasses import dataclass


@dataclass
class SedimentLayer:
    """
    Single sediment layer in a layered bottom structure.

    Parameters
    ----------
    thickness : float
        Layer thickness in meters.
    sound_speed : float
        Compressional wave speed (m/s).
    density : float
        Density (g/cm³).
    attenuation : float
        Compressional attenuation (dB/wavelength). Default 0.5.
    shear_speed : float
        Shear wave speed (m/s). Default 0.0 (fluid layer).
    shear_attenuation : float
        Shear attenuation (dB/wavelength). Default 0.0.

    Examples
    --------
    >>> sand = SedimentLayer(thickness=10, sound_speed=1650, density=1.9, attenuation=0.8)
    >>> clay = SedimentLayer(thickness=50, sound_speed=1550, density=1.5, attenuation=0.2)
    """
    thickness: float
    sound_speed: float
    density: float
    attenuation: float = 0.5
    shear_speed: float = 0.0
    shear_attenuation: float = 0.0

    def __post_init__(self):
        if self.thickness <= 0:
            raise ValueError(f"Layer thickness must be positive, got {self.thickness}")
        if self.sound_speed <= 0:
            raise ValueError(f"Layer sound_speed must be positive, got {self.sound_speed}")
        if self.density <= 0:
            raise ValueError(f"Layer density must be positive, got {self.density}")


@dataclass
class BoundaryProperties:
    """
    Properties of ocean boundaries (surface or bottom)

    Attributes
    ----------
    acoustic_type : str
        Boundary type: 'vacuum', 'rigid', 'half-space', 'grain-size', 'file'
    depth : float
        Depth of boundary (m)
    density : float
        Density (g/cm³)
    sound_speed : float
        Compressional wave speed (m/s)
    attenuation : float
        Compressional attenuation (dB/wavelength)
    roughness : float
        RMS roughness (m)
    shear_speed : float
        Shear wave speed (m/s), 0 = fluid bottom
    shear_attenuation : float
        Shear attenuation (dB/wavelength)
    grain_size_phi : float
        Mean grain size in phi units (for 'grain-size' type)
    reflection_file : str, optional
        Path to reflection coefficient file (.brc for bottom, .trc for top)
        Used when acoustic_type='file'. Can be generated by BOUNCE or OASR.
    reflection_cmin : float, optional
        Minimum phase velocity (m/s) for reflection coefficient table.
        Used when acoustic_type='file'. Default: 1400.0
    reflection_cmax : float, optional
        Maximum phase velocity (m/s) for reflection coefficient table.
        Used when acoustic_type='file'. Default: 10000.0
    reflection_rmax_km : float, optional
        Maximum range (km) for reflection coefficient sampling.
        Used when acoustic_type='file'. Default: 10.0

    Examples
    --------
    Using pre-computed reflection coefficients from BOUNCE:

    >>> # First, compute reflection coefficients
    >>> from uacpy.models import Bounce
    >>> bounce = Bounce()
    >>> result = bounce.run(env, source, receiver)
    >>> brc_file = result.data['brc_file']
    >>>
    >>> # Then use in Bellhop/Kraken/Scooter
    >>> bottom = BoundaryProperties(
    ...     acoustic_type='file',
    ...     reflection_file=brc_file
    ... )
    >>> env = Environment(name="test", depth=100, bottom=bottom)
    """

    acoustic_type: str = 'vacuum'
    depth: float = 0.0
    density: float = 1.5
    sound_speed: float = 1600.0
    attenuation: float = 0.5
    roughness: float = 0.0
    shear_speed: float = 0.0
    shear_attenuation: float = 0.0
    grain_size_phi: float = 1.0
    reflection_file: Optional[str] = None
    reflection_cmin: float = 1400.0
    reflection_cmax: float = 10000.0
    reflection_rmax_km: float = 10.0


@dataclass
class RangeDependentBottom:
    """
    Range-dependent bottom properties for realistic geoacoustic modeling

    Allows bottom acoustic properties to vary with range, essential for
    continental shelf transitions, sediment type changes, etc.

    Attributes
    ----------
    ranges_km : ndarray
        Range points in kilometers, shape (N,)
    depths : ndarray
        Bottom depth at each range in meters, shape (N,)
        Should match bathymetry if provided
    sound_speed : ndarray
        Compressional wave speed at each range (m/s), shape (N,)
    density : ndarray
        Density at each range (g/cm³), shape (N,)
    attenuation : ndarray
        Attenuation at each range (dB/wavelength), shape (N,)
    shear_speed : ndarray, optional
        Shear wave speed at each range (m/s), shape (N,). Default is 0 (fluid).
    acoustic_type : str
        Boundary type (same at all ranges): 'vacuum', 'rigid', 'half-space', etc.
        Default is 'vacuum' for consistency with BoundaryProperties.

    Examples
    --------
    Continental shelf transition (shallow to deep with sediment change):

    >>> ranges_km = np.array([0, 10, 20, 30])
    >>> depths = np.array([100, 200, 500, 1000])
    >>> sound_speed = np.array([1600, 1650, 1700, 1750])  # Hardening with depth
    >>> density = np.array([1.5, 1.7, 1.9, 2.1])
    >>> attenuation = np.array([0.5, 0.4, 0.3, 0.2])  # Less lossy deeper
    >>>
    >>> bottom_rd = RangeDependentBottom(
    ...     ranges_km=ranges_km,
    ...     depths=depths,
    ...     sound_speed=sound_speed,
    ...     density=density,
    ...     attenuation=attenuation,
    ...     shear_speed=np.zeros(4),
    ...     acoustic_type='half-space'
    ... )
    """
    ranges_km: np.ndarray
    depths: np.ndarray
    sound_speed: np.ndarray
    density: np.ndarray
    attenuation: np.ndarray
    shear_speed: np.ndarray = None
    acoustic_type: str = 'vacuum'

    def __post_init__(self):
        """Validate array lengths and set defaults."""
        n = len(self.ranges_km)

        for attr_name in ['depths', 'sound_speed', 'density', 'attenuation']:
            attr = getattr(self, attr_name)
            if len(attr) != n:
                raise ValueError(f"{attr_name} must have same length as ranges_km ({n})")

        if self.shear_speed is None:
            self.shear_speed = np.zeros(n)

    def get_at_range(self, range_m: float) -> BoundaryProperties:
        """
        Get bottom properties at a specified range by interpolation.

        Parameters
        ----------
        range_m : float
            Range in meters.

        Returns
        -------
        properties : BoundaryProperties
            Interpolated bottom properties at this range.
        """
        range_km = range_m / 1000.0
        ranges = self.ranges_km

        # Interpolate all properties
        depth = float(np.interp(range_km, ranges, self.depths))
        c_p = float(np.interp(range_km, ranges, self.sound_speed))
        rho = float(np.interp(range_km, ranges, self.density))
        alpha = float(np.interp(range_km, ranges, self.attenuation))
        c_s = float(np.interp(range_km, ranges, self.shear_speed))

        return BoundaryProperties(
            acoustic_type=self.acoustic_type,
            depth=depth,
            sound_speed=c_p,
            density=rho,
            attenuation=alpha,
            shear_speed=c_s,
        )


@dataclass
class LayeredBottom:
    """
    Depth-dependent (layered) sediment structure.

    Defines a stack of sediment layers above a deepest half-space.
    Used by models that support multi-layered bottoms (Kraken, Scooter,
    SPARC via NMEDIA > 1; OASES via layered format).

    Parameters
    ----------
    layers : list of SedimentLayer
        Sediment layers from top (shallowest) to bottom (deepest),
        stacked below the water column.
    halfspace : BoundaryProperties
        Properties of the deepest half-space below all layers.

    Examples
    --------
    Continental shelf with sand over clay over rock:

    >>> from uacpy.core.environment import SedimentLayer, LayeredBottom, BoundaryProperties
    >>> bottom = LayeredBottom(
    ...     layers=[
    ...         SedimentLayer(thickness=10, sound_speed=1550, density=1.3, attenuation=0.5),
    ...         SedimentLayer(thickness=50, sound_speed=1650, density=1.7, attenuation=0.3),
    ...     ],
    ...     halfspace=BoundaryProperties(
    ...         acoustic_type='half-space',
    ...         sound_speed=1800, density=2.0, attenuation=0.1
    ...     )
    ... )
    """
    layers: List[SedimentLayer]
    halfspace: BoundaryProperties

    def __post_init__(self):
        if not self.layers:
            raise ValueError("LayeredBottom requires at least one SedimentLayer")

    def total_thickness(self) -> float:
        """Total thickness of all sediment layers (m)."""
        return sum(layer.thickness for layer in self.layers)

    def layer_depths(self, seafloor_depth: float) -> List[Tuple[float, float]]:
        """
        Compute (top_depth, bottom_depth) for each layer.

        Parameters
        ----------
        seafloor_depth : float
            Depth of the seafloor (top of first layer) in meters.

        Returns
        -------
        list of (float, float)
            (top_depth, bottom_depth) pairs for each layer.
        """
        depths = []
        current_depth = seafloor_depth
        for layer in self.layers:
            top = current_depth
            bottom = current_depth + layer.thickness
            depths.append((top, bottom))
            current_depth = bottom
        return depths


@dataclass
class RangeDependentLayeredBottom:
    """
    Range-dependent layered sediment: a LayeredBottom at each range point.

    Combines range variation (different sediment stacks along the
    propagation path) with depth variation (multiple layers at each
    range).  RAM maps each stack to its 4-point sediment profile;
    AT models (Kraken/Scooter/SPARC) warn because NMEDIA is fixed.

    Parameters
    ----------
    ranges_km : ndarray
        Range points in kilometers, shape (N,).
    depths : ndarray
        Bathymetry at each range in meters, shape (N,).
    profiles : list of LayeredBottom
        One LayeredBottom per range point (length N).

    Examples
    --------
    Mud-over-clay near-shore transitioning to sand-over-rock offshore:

    >>> from uacpy.core.environment import (
    ...     SedimentLayer, LayeredBottom, BoundaryProperties,
    ...     RangeDependentLayeredBottom,
    ... )
    >>> near = LayeredBottom(
    ...     layers=[SedimentLayer(5, 1500, 1.2, 1.0),
    ...             SedimentLayer(15, 1550, 1.4, 0.8)],
    ...     halfspace=BoundaryProperties(acoustic_type='half-space',
    ...                                  sound_speed=1800, density=2.0, attenuation=0.1),
    ... )
    >>> far = LayeredBottom(
    ...     layers=[SedimentLayer(3, 1650, 1.8, 0.3),
    ...             SedimentLayer(10, 1750, 2.0, 0.2)],
    ...     halfspace=BoundaryProperties(acoustic_type='half-space',
    ...                                  sound_speed=2200, density=2.5, attenuation=0.05),
    ... )
    >>> rdl = RangeDependentLayeredBottom(
    ...     ranges_km=np.array([0, 20]),
    ...     depths=np.array([100, 300]),
    ...     profiles=[near, far],
    ... )
    """
    ranges_km: np.ndarray
    depths: np.ndarray
    profiles: List[LayeredBottom]

    def __post_init__(self):
        n = len(self.ranges_km)
        if len(self.depths) != n:
            raise ValueError(
                f"depths length ({len(self.depths)}) must match "
                f"ranges_km length ({n})"
            )
        if len(self.profiles) != n:
            raise ValueError(
                f"profiles length ({len(self.profiles)}) must match "
                f"ranges_km length ({n})"
            )
        if n < 1:
            raise ValueError("At least one range point is required")

    def max_total_thickness(self) -> float:
        """Maximum total sediment thickness across all range points."""
        return max(p.total_thickness() for p in self.profiles)

    def get_at_range(self, range_m: float) -> 'LayeredBottom':
        """Return the nearest LayeredBottom profile for a given range (m)."""
        range_km = range_m / 1000.0
        idx = int(np.argmin(np.abs(self.ranges_km - range_km)))
        return self.profiles[idx]

    def sample_at_depths(
        self,
        profile_idx: int,
        n_points: int = 4,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Sample a LayeredBottom profile at evenly-spaced depth points.

        Returns arrays of (sound_speed, density, attenuation) sampled at
        ``n_points`` depths spanning [0, max_total_thickness].  Used by RAM
        to map arbitrary layers to its fixed 4-point sediment grid.

        Parameters
        ----------
        profile_idx : int
            Index into ``self.profiles``.
        n_points : int
            Number of sample points (default 4, matching RAM).

        Returns
        -------
        cs : ndarray, shape (n_points,)
            Sound speed at each depth sample.
        rho : ndarray, shape (n_points,)
            Density at each depth sample.
        attn : ndarray, shape (n_points,)
            Attenuation at each depth sample.
        """
        lb = self.profiles[profile_idx]
        max_thick = self.max_total_thickness()
        if max_thick <= 0:
            max_thick = 1.0
        sample_depths = np.linspace(0, max_thick, n_points)

        cs = np.empty(n_points)
        rho = np.empty(n_points)
        attn = np.empty(n_points)

        for i, d in enumerate(sample_depths):
            # Walk through layers to find which layer this depth falls in
            cumulative = 0.0
            found = False
            for layer in lb.layers:
                if d <= cumulative + layer.thickness:
                    cs[i] = layer.sound_speed
                    rho[i] = layer.density
                    attn[i] = layer.attenuation
                    found = True
                    break
                cumulative += layer.thickness
            if not found:
                # Below all layers → halfspace
                cs[i] = lb.halfspace.sound_speed
                rho[i] = lb.halfspace.density
                attn[i] = lb.halfspace.attenuation

        return cs, rho, attn


def generate_sea_surface(
    max_range_m: float,
    wind_speed_ms: float = 10.0,
    n_points: int = 500,
    seed: Optional[int] = None,
) -> np.ndarray:
    """
    Generate a random sea surface realization from the Pierson-Moskowitz spectrum.

    Parameters
    ----------
    max_range_m : float
        Maximum range in meters.
    wind_speed_ms : float
        Wind speed at 10 m height in m/s. Typical values:
        - 5 m/s: calm (sea state 2-3, Hs ~ 0.3 m)
        - 10 m/s: moderate (sea state 4, Hs ~ 1.2 m)
        - 15 m/s: rough (sea state 5, Hs ~ 2.8 m)
        - 20 m/s: very rough (sea state 6, Hs ~ 5.0 m)
    n_points : int
        Number of range points in the output altimetry array.
    seed : int, optional
        Random seed for reproducibility.

    Returns
    -------
    altimetry : ndarray, shape (n_points, 2)
        Column 0: range (m), Column 1: surface height (m, positive up).
        Suitable for passing directly to ``Environment(altimetry=...)``.
    """
    g = 9.81
    rng = np.random.default_rng(seed)

    ranges = np.linspace(0, max_range_m, n_points)
    dx = ranges[1] - ranges[0]

    # Spatial frequency grid (cycles/m)
    n_fft = n_points
    dk = 1.0 / (n_fft * dx)  # spatial freq resolution
    k = np.arange(1, n_fft // 2 + 1) * dk  # positive frequencies
    omega = np.sqrt(g * 2 * np.pi * k)  # deep-water dispersion: omega^2 = g*k_wave

    # Pierson-Moskowitz spectrum S(omega)
    # S(omega) = (alpha * g^2 / omega^5) * exp(-beta * (omega_p / omega)^4)
    alpha_pm = 8.1e-3
    beta_pm = 0.74
    omega_p = g / wind_speed_ms  # peak angular frequency
    S_omega = (alpha_pm * g**2 / omega**5) * np.exp(-beta_pm * (omega_p / omega)**4)

    # Convert to spatial spectrum S(k) via S(k) = S(omega) * domega/dk
    # domega/dk = g / (2*omega) for deep water
    domega_dk = g / (2 * omega)
    S_k = S_omega * domega_dk

    # Generate random amplitudes from spectrum
    amplitude = np.sqrt(2 * S_k * dk)
    phase = rng.uniform(0, 2 * np.pi, len(k))

    # Synthesize surface via inverse Fourier (sum of sinusoids)
    surface = np.zeros(n_points)
    for i, ki in enumerate(k):
        surface += amplitude[i] * np.cos(2 * np.pi * ki * ranges + phase[i])

    return np.column_stack([ranges, surface])


class Environment:
    """
    Ocean environment definition

    Defines the complete acoustic environment including sound speed profile,
    bathymetry, surface/bottom properties, and water column parameters.

    Parameters
    ----------
    name : str
        Environment name/identifier
    depth : float
        Maximum water depth in meters
    ssp_type : str, optional
        Sound speed profile *shape* or *interpolation* hint:
        'isovelocity', 'linear', 'bilinear', 'munk' (shapes),
        'pchip', 'cubic', 'analytic', 'n2linear', 'quad' (interpolation).
        Default is 'isovelocity'.

        Note: shape names ('munk', 'isovelocity') and interpolation
        names ('pchip', 'n2linear') are currently conflated in this
        single field. Writers treat shape names as the default
        interpolation (C-Linear).
    ssp_data : array-like, optional
        SSP data as [(depth, sound_speed), ...] pairs for 1D (range-independent).
        Required for most ssp_types except 'isovelocity'.
        Also required alongside ``ssp_2d_matrix`` to specify the depth axis.
    ssp_2d_ranges : array-like, optional
        Range points (km) for 2D range-dependent SSP. If provided, requires ssp_2d_matrix.
    ssp_2d_matrix : array-like, optional
        2D sound speed matrix c(depth, range), shape (n_depth, n_range).
        Requires ssp_2d_ranges. For use with Bellhop 'quad' mode or RAM.
    sound_speed : float, optional
        Sound speed for 'isovelocity' profile. Default is 1500 m/s.
    bathymetry : array-like, optional
        Range-dependent bathymetry as [(range, depth), ...] pairs.
        Default is flat bottom at specified depth.
    altimetry : array-like, optional
        Range-dependent surface altimetry as [(range_m, height_m), ...] pairs.
        Height is positive up from sea level (0), negative below (e.g. ice keels).
        When provided, Bellhop/Kraken/Scooter write a .ati file for rough surface.
        Default is None (flat surface).
    bottom : BoundaryProperties or RangeDependentBottom, optional
        Bottom boundary properties. Can be single BoundaryProperties or
        RangeDependentBottom for range-varying geoacoustic properties.
        Default is rigid half-space.
    surface : BoundaryProperties, optional
        Surface boundary properties. Default is vacuum (pressure release).
    attenuation : float, optional
        Volume attenuation in dB/wavelength. Default is 0.0.

    Attributes
    ----------
    name : str
        Environment name
    depth : float
        Maximum water depth
    ssp_type : str
        SSP type
    ssp_data : ndarray
        SSP data array
    sound_speed : float
        Reference sound speed
    bathymetry : ndarray
        Bathymetry data
    altimetry : ndarray or None
        Surface altimetry data, shape (N, 2) as (range_m, height_m)
    bottom : BoundaryProperties
        Bottom properties
    surface : BoundaryProperties
        Surface properties
    attenuation : float
        Volume attenuation

    Examples
    --------
    Simple isovelocity environment:

    >>> env = Environment(name='shallow', depth=100, sound_speed=1500)

    Linear SSP:

    >>> env = Environment(
    ...     name='test',
    ...     depth=200,
    ...     ssp_type='linear',
    ...     ssp_data=[(0, 1520), (200, 1480)]
    ... )

    Range-dependent bathymetry:

    >>> env = Environment(
    ...     name='slope',
    ...     depth=1000,
    ...     bathymetry=[(0, 100), (5000, 500), (10000, 1000)]
    ... )

    Munk profile:

    >>> env = Environment(name='deep', depth=5000, ssp_type='munk')
    """

    def __init__(
        self,
        name: str,
        depth: float,
        ssp_type: str = 'isovelocity',
        ssp_data: Optional[Union[List[Tuple[float, float]], np.ndarray]] = None,
        ssp_2d_ranges: Optional[np.ndarray] = None,
        ssp_2d_matrix: Optional[np.ndarray] = None,
        sound_speed: float = 1500.0,
        bathymetry: Optional[Union[List[Tuple[float, float]], np.ndarray]] = None,
        altimetry: Optional[Union[List[Tuple[float, float]], np.ndarray]] = None,
        bottom: Optional[Union[BoundaryProperties, RangeDependentBottom, 'LayeredBottom', 'RangeDependentLayeredBottom']] = None,
        surface: Optional[BoundaryProperties] = None,
        attenuation: float = 0.0,
    ):
        self.name = name
        self.depth = float(depth)
        self.ssp_type = ssp_type.lower()
        self.sound_speed = sound_speed
        self.attenuation = attenuation

        # Validate depth
        if self.depth <= 0:
            raise ValueError(f"Environment depth must be positive, got {self.depth}")

        # Validate SSP type
        valid_ssp_types = [
            'isovelocity', 'linear', 'bilinear', 'munk',
            'pchip', 'cubic', 'analytic', 'n2linear', 'quad'
        ]
        if self.ssp_type not in valid_ssp_types:
            raise ValueError(f"ssp_type must be one of {valid_ssp_types}")

        # Set 2D SSP (range-dependent) if provided
        if ssp_2d_ranges is not None or ssp_2d_matrix is not None:
            if ssp_2d_ranges is None or ssp_2d_matrix is None:
                raise ValueError("Both ssp_2d_ranges and ssp_2d_matrix must be provided together")

            self.ssp_2d_ranges = np.array(ssp_2d_ranges, dtype=np.float64)  # km
            self.ssp_2d_matrix = np.array(ssp_2d_matrix, dtype=np.float64)

            if self.ssp_2d_matrix.shape[1] != len(self.ssp_2d_ranges):
                raise ValueError(
                    f"ssp_2d_matrix columns ({self.ssp_2d_matrix.shape[1]}) "
                    f"must match ssp_2d_ranges length ({len(self.ssp_2d_ranges)})"
                )

            # For 2D SSP we MUST have a real depth axis; fabricating
            # np.arange(n_depth) silently puts the ocean at z=[0..n_depth-1]
            # which corrupts every model that reads env.ssp_data[:, 0].
            if ssp_data is None:
                raise ValueError(
                    "ssp_2d_matrix requires either ssp_data (1D reference "
                    "with depth column) or an explicit depth axis. "
                    "Provide ssp_data=[(z0, c0), (z1, c1), ...] so the "
                    "depth axis for the 2D matrix is defined."
                )
            self.ssp_data = np.array(ssp_data, dtype=np.float64)
        else:
            # 1D SSP (range-independent)
            self.ssp_2d_ranges = None
            self.ssp_2d_matrix = None

            # Set SSP data
            if ssp_data is not None:
                self.ssp_data = np.array(ssp_data, dtype=np.float64)
                if self.ssp_data.shape[1] != 2:
                    raise ValueError("ssp_data must have shape (N, 2) as (depth, sound_speed)")
            elif ssp_type == 'isovelocity':
                self.ssp_data = np.array([[0.0, sound_speed], [depth, sound_speed]])
            elif ssp_type == 'munk':
                # Generate Munk profile
                self.ssp_data = self._generate_munk_profile(depth)
            else:
                raise ValueError(f"ssp_data required for ssp_type='{ssp_type}'")

        # Set bathymetry
        if bathymetry is not None:
            self.bathymetry = np.array(bathymetry, dtype=np.float64)
            if self.bathymetry.shape[1] != 2:
                raise ValueError("bathymetry must have shape (N, 2) as (range, depth)")
        else:
            # Flat bottom
            self.bathymetry = np.array([[0.0, depth]], dtype=np.float64)

        # Set altimetry (surface roughness / wave profile)
        if altimetry is not None:
            self.altimetry = np.array(altimetry, dtype=np.float64)
            if self.altimetry.ndim != 2 or self.altimetry.shape[1] != 2:
                raise ValueError("altimetry must have shape (N, 2) as (range_m, height_m)")
        else:
            self.altimetry = None

        # CRITICAL: Extend SSP to maximum bathymetry depth if needed
        max_bathy_depth = np.max(self.bathymetry[:, 1])
        if max_bathy_depth > self.ssp_data[-1, 0]:
            # SSP doesn't cover full bathymetry depth - extend it
            last_sound_speed = self.ssp_data[-1, 1]
            self.ssp_data = np.vstack([
                self.ssp_data,
                [max_bathy_depth, last_sound_speed]
            ])

            # Also extend ssp_2d_matrix if present to keep dimensions consistent
            if self.ssp_2d_matrix is not None:
                # Add row with last sound speed values for each range
                last_row = self.ssp_2d_matrix[-1, :]
                self.ssp_2d_matrix = np.vstack([
                    self.ssp_2d_matrix,
                    last_row
                ])

        # Set boundary properties
        if surface is None:
            self.surface = BoundaryProperties(
                acoustic_type='vacuum',
                depth=0.0
            )
        else:
            self.surface = surface

        # Set bottom boundary properties
        self.bottom_layered = None
        self.bottom_rd_layered = None
        if bottom is None:
            # Default: single range-independent bottom
            self.bottom = BoundaryProperties(
                acoustic_type='half-space',
                depth=depth,
                density=1.5,
                sound_speed=1600.0,
                attenuation=0.5
            )
            self.bottom_rd = None
        elif isinstance(bottom, RangeDependentBottom):
            # Range-dependent bottom
            self.bottom_rd = bottom
            # Set self.bottom to median-range properties so range-independent
            # models that read env.bottom pick a representative profile. Using
            # range=0 would pick one extreme (e.g., soft mud) and skew TL.
            median_range_m = float(np.median(bottom.ranges_km)) * 1000.0
            self.bottom = bottom.get_at_range(median_range_m)
        elif isinstance(bottom, RangeDependentLayeredBottom):
            # Range-AND-depth-dependent bottom
            self.bottom_rd_layered = bottom
            # Use median-range profile's halfspace as the representative
            # env.bottom. Deep-copy so we don't mutate the caller's halfspace
            # object when we overwrite its depth field below.
            mid_idx = len(bottom.profiles) // 2
            self.bottom = _copy.deepcopy(bottom.profiles[mid_idx].halfspace)
            self.bottom.depth = depth
            # No scalar bottom_rd (models must handle rd_layered directly)
            self.bottom_rd = None
            # Set bathymetry from the depth array if flat
            if len(self.bathymetry) <= 1:
                self.bathymetry = np.column_stack([
                    bottom.ranges_km * 1000.0,
                    bottom.depths,
                ])
        elif isinstance(bottom, LayeredBottom):
            # Layered (depth-dependent) bottom
            self.bottom_layered = bottom
            # Deep-copy halfspace so we don't mutate caller's object.
            self.bottom = _copy.deepcopy(bottom.halfspace)
            self.bottom.depth = depth
            self.bottom_rd = None
        else:
            # Single BoundaryProperties — deep-copy so setting .depth
            # doesn't leak back into the caller's object.
            self.bottom = _copy.deepcopy(bottom)
            if not isinstance(self.bottom, RangeDependentBottom):
                self.bottom.depth = depth
            self.bottom_rd = None

    @staticmethod
    def _generate_munk_profile(max_depth: float, n_points: int = 101) -> np.ndarray:
        """
        Generate Munk canonical sound speed profile

        Parameters
        ----------
        max_depth : float
            Maximum depth
        n_points : int
            Number of profile points

        Returns
        -------
        profile : ndarray
            Profile as (depth, sound_speed) pairs
        """
        depths = np.linspace(0, max_depth, n_points)
        z_axis = 1300.0  # Axis depth
        epsilon = 0.00737  # Perturbation parameter
        c_min = 1500.0  # Minimum sound speed

        # Munk profile
        eta = 2 * (depths - z_axis) / z_axis
        c = c_min * (1 + epsilon * (eta - 1 + np.exp(-eta)))

        return np.column_stack([depths, c])

    def get_sound_speed(self, depth: Union[float, np.ndarray]) -> np.ndarray:
        """
        Get sound speed at specified depth(s)

        Parameters
        ----------
        depth : float or array-like
            Depth(s) in meters

        Returns
        -------
        sound_speed : float or ndarray
            Sound speed(s) in m/s
        """
        depth = np.atleast_1d(depth)

        if self.ssp_type == 'isovelocity':
            return np.full_like(depth, self.sound_speed)

        # Interpolate from SSP data
        return np.interp(depth, self.ssp_data[:, 0], self.ssp_data[:, 1])

    def get_bathymetry_depth(self, range_m: Union[float, np.ndarray]) -> np.ndarray:
        """
        Get bathymetry depth at specified range(s)

        Parameters
        ----------
        range_m : float or array-like
            Range(s) in meters

        Returns
        -------
        depth : float or ndarray
            Bathymetry depth(s) in meters
        """
        range_m = np.atleast_1d(range_m)

        if len(self.bathymetry) == 1:
            # Flat bottom
            return np.full_like(range_m, self.bathymetry[0, 1])

        # Interpolate bathymetry
        return np.interp(range_m, self.bathymetry[:, 0], self.bathymetry[:, 1])

    def get_ssp_at_range(self, range_m: float) -> np.ndarray:
        """
        Get sound speed profile at specified range

        For range-dependent SSP (2D), interpolates between range profiles.
        For range-independent SSP (1D), returns the same profile.

        Parameters
        ----------
        range_m : float
            Range in meters

        Returns
        -------
        ssp : ndarray
            Sound speed profile as (depth, sound_speed) pairs, shape (N, 2)
        """
        if self.ssp_2d_matrix is None:
            # Range-independent: return the standard 1D SSP
            return self.ssp_data.copy()

        # Range-dependent: interpolate across range
        range_km = range_m / 1000.0

        if range_km <= self.ssp_2d_ranges[0]:
            # Before first range point
            c_profile = self.ssp_2d_matrix[:, 0]
        elif range_km >= self.ssp_2d_ranges[-1]:
            # After last range point
            c_profile = self.ssp_2d_matrix[:, -1]
        else:
            # Interpolate between range profiles
            c_profile = np.zeros(self.ssp_2d_matrix.shape[0])
            for i_depth in range(self.ssp_2d_matrix.shape[0]):
                c_profile[i_depth] = np.interp(
                    range_km,
                    self.ssp_2d_ranges,
                    self.ssp_2d_matrix[i_depth, :]
                )

        # Return as (depth, c) pairs - use depths from ssp_data
        depths = self.ssp_data[:, 0]
        return np.column_stack([depths, c_profile])

    def get_bottom_at_range(self, range_m: float):
        """
        Get bottom properties at specified range.

        Returns a ``LayeredBottom`` when the environment has layered
        sediment, otherwise a ``BoundaryProperties``.

        Parameters
        ----------
        range_m : float
            Range in meters

        Returns
        -------
        bottom : BoundaryProperties or LayeredBottom
            Bottom properties at this range
        """
        if self.bottom_rd_layered is not None:
            return self.bottom_rd_layered.get_at_range(range_m)
        if self.bottom_layered is not None:
            return self.bottom_layered
        if self.bottom_rd is not None:
            return self.bottom_rd.get_at_range(range_m)
        # Range-independent: return copy of standard bottom
        # Update depth from bathymetry if range-dependent bathy
        if len(self.bathymetry) > 1:
            depth_at_range = float(np.asarray(self.get_bathymetry_depth(range_m)).flat[0])
            from copy import deepcopy
            bottom_copy = deepcopy(self.bottom)
            bottom_copy.depth = depth_at_range
            return bottom_copy
        return self.bottom

    def has_range_dependent_ssp(self) -> bool:
        """Return True if the environment has a range-dependent SSP."""
        return self.ssp_2d_matrix is not None

    def has_range_dependent_bottom(self) -> bool:
        """Return True if bottom properties vary with range."""
        return self.bottom_rd is not None

    def has_layered_bottom(self) -> bool:
        """Return True if the environment has a layered (depth-dependent) bottom."""
        return self.bottom_layered is not None

    def has_range_dependent_layered_bottom(self) -> bool:
        """Return True if the environment has a range-dependent layered bottom."""
        return self.bottom_rd_layered is not None

    @property
    def is_range_dependent(self) -> bool:
        """
        Check if environment has range-dependent properties

        Returns True if any of the following vary with range:
        - Bathymetry (more than 1 range point AND depths actually differ)
        - SSP (2D matrix provided)
        - Bottom properties (range-dependent bottom object)

        A bathymetry array of two identical-depth points [(0, d), (rmax, d)]
        is treated as range-independent (it is just a range extent marker).
        """
        # Bathymetry is only range-dependent if the depths actually differ.
        has_rd_bathy = False
        if len(self.bathymetry) > 1:
            depths = self.bathymetry[:, 1]
            if not np.allclose(depths, depths[0]):
                has_rd_bathy = True
        has_rd_ssp = hasattr(self, 'ssp_2d_matrix') and self.ssp_2d_matrix is not None
        has_rd_bottom = hasattr(self, 'bottom_rd') and self.bottom_rd is not None
        has_rdl_bottom = hasattr(self, 'bottom_rd_layered') and self.bottom_rd_layered is not None

        return has_rd_bathy or has_rd_ssp or has_rd_bottom or has_rdl_bottom

    def __repr__(self) -> str:
        range_dep = "range-dep" if self.is_range_dependent else "range-indep"
        return (f"Environment(name='{self.name}', depth={self.depth:.1f}m, "
                f"ssp='{self.ssp_type}', {range_dep})")

    def get_representative_depth(self, method: str = 'median') -> float:
        """
        Get representative depth from range-dependent bathymetry

        For models that don't support range-dependent environments,
        this provides a single representative depth value.

        Parameters
        ----------
        method : str, optional
            Method for computing representative value:
            - 'median': Median depth (default, most robust)
            - 'mean': Mean depth
            - 'min': Minimum depth (shallowest)
            - 'max': Maximum depth (deepest)
            - 'initial': Initial depth at range=0

        Returns
        -------
        depth : float
            Representative depth in meters

        Examples
        --------
        >>> env = Environment(name='slope', depth=100,
        ...                   bathymetry=[(0, 100), (5000, 200), (10000, 300)])
        >>> env.get_representative_depth('median')
        200.0
        >>> env.get_representative_depth('mean')
        200.0
        >>> env.get_representative_depth('initial')
        100.0
        """
        depths = self.bathymetry[:, 1]

        if method == 'median':
            return float(np.median(depths))
        elif method == 'mean':
            return float(np.mean(depths))
        elif method == 'min':
            return float(np.min(depths))
        elif method == 'max':
            return float(np.max(depths))
        elif method == 'initial':
            return float(depths[0])
        else:
            raise ValueError(f"Unknown method '{method}'. Use 'median', 'mean', 'min', 'max', or 'initial'")

    def get_range_independent_approximation(self, method: str = 'median'):
        """
        Create a range-independent approximation of this environment

        For models that don't support range-dependent environments, this
        creates a simplified copy with single representative depth.

        Parameters
        ----------
        method : str, optional
            Method for computing representative depth.
            See get_representative_depth() for options.
            Default is 'median'.

        Returns
        -------
        env : Environment
            New range-independent environment

        Examples
        --------
        >>> env_rd = Environment(name='slope', depth=100,
        ...                      bathymetry=[(0, 100), (10000, 300)])
        >>> env_ri = env_rd.get_range_independent_approximation()
        >>> env_ri.is_range_dependent
        False
        >>> env_ri.depth
        200.0
        """
        representative_depth = self.get_representative_depth(method)

        # Adjust SSP to match representative depth
        ssp_data_adjusted = self.ssp_data.copy()

        if representative_depth > ssp_data_adjusted[-1, 0]:
            # Extend: Add point at representative depth with same sound speed as last point
            last_c = float(ssp_data_adjusted[-1, 1])
            ssp_data_adjusted = np.vstack([ssp_data_adjusted, [representative_depth, last_c]])

        elif representative_depth < ssp_data_adjusted[-1, 0]:
            # Truncate/interpolate: SSP extends beyond representative depth
            # Keep points up to representative depth, add interpolated point at representative depth
            mask = ssp_data_adjusted[:, 0] <= representative_depth
            ssp_data_adjusted = ssp_data_adjusted[mask]

            # Add interpolated point at representative depth if not already there
            if ssp_data_adjusted[-1, 0] < representative_depth:
                # Interpolate sound speed at representative depth
                from scipy.interpolate import interp1d
                if self.ssp_type == 'pchip':
                    from scipy.interpolate import PchipInterpolator
                    interp_func = PchipInterpolator(self.ssp_data[:, 0], self.ssp_data[:, 1])
                else:
                    # Use constant extrapolation (safest for sound speed)
                    # Prevents non-physical values from unbounded extrapolation
                    ssp_speeds = self.ssp_data[:, 1]
                    interp_func = interp1d(
                        self.ssp_data[:, 0], ssp_speeds,
                        kind='linear',
                        bounds_error=False,
                        fill_value=(ssp_speeds[0], ssp_speeds[-1])
                    )

                c_at_depth = float(interp_func(representative_depth))
                ssp_data_adjusted = np.vstack([ssp_data_adjusted, [representative_depth, c_at_depth]])

        return Environment(
            name=f"{self.name} (range-independent approx)",
            depth=representative_depth,
            ssp_type=self.ssp_type,
            ssp_data=ssp_data_adjusted,
            sound_speed=self.sound_speed,
            bathymetry=None,  # Will create flat bottom at representative_depth
            bottom=self.bottom,
            surface=self.surface,
            attenuation=self.attenuation,
        )

    def copy(self):
        """Create a deep copy of the environment.

        Uses copy.deepcopy so every field — including ssp_2d_ranges,
        ssp_2d_matrix, altimetry, bottom_layered, bottom_rd_layered, and
        bottom_rd — is duplicated without aliasing back to the original
        instance.
        """
        return _copy.deepcopy(self)
