"""The harmonisation gates: one rule each over the public API read as one
surface (``uacpy.__all__`` and the ``__all__`` of every submodule ``uacpy``
exposes), or over the package source by AST.

Each gate measures its offenders and compares them with an explicit list of
the known ones still open. The list may only shrink: a new offender fails the
gate, and so does a listed one that is gone (delete its entry).
"""
import ast
import importlib
import inspect
import json
import re
import warnings
from pathlib import Path

import uacpy
from uacpy.core import constants

_PACKAGE = Path(uacpy.__file__).resolve().parent

#: The known offenders of the ratchet gates, by gate (one list per key; the
#: lists only shrink). Regenerated by nothing: an entry is deleted by hand
#: when its offence is fixed, and the gate refuses a new one.
_RATCHET = {key: frozenset(values) for key, values in json.loads(
    (Path(__file__).parent / 'data' / 'harmonisation_ratchets.json')
    .read_text(encoding='utf-8')).items()}


# ── the public surface ────────────────────────────────────────────────────

def _public_objects():
    """``(label, object)`` for every public name: the root's ``__all__``, the
    ``__all__`` of each lazily exposed submodule, ``uacpy.core`` and
    ``uacpy.core.results``, each object once."""
    modules = ['uacpy', *uacpy._LAZY_SUBMODULES.values(), 'uacpy.core',
               'uacpy.core.results']
    seen, out = set(), []
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        for name in modules:
            mod = importlib.import_module(name)
            for attr in getattr(mod, '__all__', ()):
                obj = getattr(mod, attr, None)
                if obj is None or inspect.ismodule(obj) or id(obj) in seen:
                    continue
                seen.add(id(obj))
                out.append((f'{name}.{attr}', obj))
    return out


def _signature(obj):
    try:
        return inspect.signature(obj)
    except (TypeError, ValueError):
        return None


def _public_callables():
    """``(label, callable)`` for every public function, public class (its
    constructor) and public method a public class defines."""
    out = []
    for label, obj in _public_objects():
        if inspect.isclass(obj):
            if issubclass(obj, BaseException):
                continue
            out.append((label, obj))
            for name, member in vars(obj).items():
                if name.startswith('_'):
                    continue
                if isinstance(member, (staticmethod, classmethod)):
                    member = member.__func__
                if inspect.isfunction(member):
                    out.append((f'{label}.{name}', member))
        elif callable(obj):
            out.append((label, obj))
    return out


def _parameters():
    """``(label, Parameter)`` for every parameter of every public callable,
    ``self``/``cls`` and ``*args``/``**kwargs`` left out."""
    for label, obj in _public_callables():
        sig = _signature(obj)
        if sig is None:
            continue
        for p in sig.parameters.values():
            if p.name in ('self', 'cls') or p.kind in (p.VAR_POSITIONAL,
                                                       p.VAR_KEYWORD):
                continue
            yield label, p


def _package_trees():
    """``(relative path, ast tree)`` of every package module (tests,
    examples and third_party left out)."""
    for path in sorted(_PACKAGE.rglob('*.py')):
        rel = path.relative_to(_PACKAGE).as_posix()
        if rel.split('/')[0] in ('tests', 'examples', 'third_party'):
            continue
        yield rel, ast.parse(path.read_text(encoding='utf-8'))


def _check(measured, known, what):
    new = sorted(set(measured) - set(known))
    gone = sorted(set(known) - set(measured))
    problems = [f'new {what}: {x}' for x in new] + \
        [f'{what} gone, delete its entry: {x}' for x in gone]
    assert not problems, '\n'.join(problems)


# ── rule 1: one word per idea ─────────────────────────────────────────────

def _type_of(p):
    """The annotation of ``p`` as text, ``Optional[...]`` and ``None``
    unions reduced to the inner type; ``None`` when it has none."""
    ann = p.annotation
    if ann is p.empty:
        return None
    text = ann if isinstance(ann, str) else \
        ann.__name__ if isinstance(ann, type) else str(ann)
    text = text.replace('typing.', '')
    if text == 'Any':
        return None
    text = re.sub(r'^Optional\[(.*)\]$', r'\1', text)
    text = re.sub(r'\s*\|\s*None$', '', text)
    return text


#: Words that name a carrier wherever they name a parameter.
_CARRIER_WORDS = {'env': 'Environment', 'environment': 'Environment',
                  'receiver': 'Receiver'}


def _carrier_words_naming_something_else():
    return {f'{label}({p.name}: {_type_of(p)})' for label, p in _parameters()
            if p.name in _CARRIER_WORDS and _type_of(p) is not None
            and _CARRIER_WORDS[p.name] not in _type_of(p)}


def test_a_carrier_word_names_its_carrier():
    """``env``, ``environment`` and ``receiver`` name their carrier in every
    public signature that annotates them. H2's known case: ``environment``
    was a Hamilton & Bachman fit string in the grain-size chain (now
    ``hamilton_fit``)."""
    offenders = sorted(_carrier_words_naming_something_else())
    assert not offenders, offenders


#: Names that read ``max_<thing>`` / ``min_<thing>`` because they are caps
#: (at most so many points, so far, so many days), not the largest value of
#: a quantity.
_CAPS = frozenset({'max_points', 'max_order', 'max_distance_km', 'max_days',
                   'min_gap', 'max_depths', 'max_deg', 'min_deg',
                   'max_miss', 'max_launches'})


def _prefix_bounds():
    out = set()
    for label, obj in _public_callables():
        name = label.rsplit('.', 1)[-1]
        if re.match(r'^(max|min)_', name) and name not in _CAPS:
            out.add(label)
        sig = _signature(obj)
        for p in (sig.parameters.values() if sig else ()):
            if re.match(r'^(max|min)_', p.name) and p.name not in _CAPS:
                out.add(f'{label}({p.name})')
    for label, obj in _public_objects():
        if inspect.isclass(obj):
            for name, member in vars(obj).items():
                if isinstance(member, property) and \
                        re.match(r'^(max|min)_', name) and name not in _CAPS:
                    out.add(f'{label}.{name}')
    return out


#: Prefix bounds still open.
_PREFIX_BOUNDS = _RATCHET.get('prefix_bounds', frozenset())


def test_a_bound_is_spelt_quantity_then_bound():
    """The largest value of a quantity, or an interval's upper end, is
    ``<quantity>_max`` (``range_max``, ``depth_max``, ``freq_max``); the
    prefix form is kept for caps only (:data:`_CAPS`). H4's known case:
    ``Environment.max_range`` beside ``Receiver.range_max``."""
    _check(_prefix_bounds(), _PREFIX_BOUNDS, 'prefix bound')


#: Pairs of keywords that name one argument.
_SYNONYM_PAIRS = (('ax', 'axes'), ('angle', 'theta'))


def _synonym_keywords():
    out = set()
    for label, obj in _public_callables():
        sig = _signature(obj)
        names = set(sig.parameters) if sig else set()
        for a, b in _SYNONYM_PAIRS:
            if a in names and b in names:
                out.add(f'{label}({a}, {b})')
    return out


#: Synonym pairs still open.
_SYNONYMS = _RATCHET.get('synonyms', frozenset())


def test_one_keyword_per_argument():
    """No public signature takes two keywords for one value: H10's known
    case was ``plot_transfer_function(axes=, ax=)``."""
    _check(_synonym_keywords(), _SYNONYMS, 'synonym pair')


# ── rule 2: the dB reference ──────────────────────────────────────────────

_REFERENCE_NAMES = ('REFERENCE_PRESSURE_WATER', 'REFERENCE_PRESSURE_AIR')


def _default_pairs(fn):
    a = fn.args
    pos = a.posonlyargs + a.args
    return list(zip(pos[len(pos) - len(a.defaults):], a.defaults)) + \
        [(x, d) for x, d in zip(a.kwonlyargs, a.kw_defaults) if d is not None]


def _name_of(node):
    return node.id if isinstance(node, ast.Name) else \
        node.attr if isinstance(node, ast.Attribute) else None


def _reference_offenders():
    out = set()
    for rel, tree in _package_trees():
        for fn in ast.walk(tree):
            if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)) or \
                    fn.name.startswith('_') and fn.name != '__init__':
                continue
            for arg, default in _default_pairs(fn):
                named = _name_of(default)
                if named in _REFERENCE_NAMES and arg.arg != 'ref':
                    out.add(f'{rel} {fn.name}({arg.arg})')
                if arg.arg == 'ref' and named not in _REFERENCE_NAMES and \
                        not (isinstance(default, ast.Constant)
                             and default.value is None):
                    out.add(f'{rel} {fn.name}(ref={ast.unparse(default)})')
    return out


def test_the_dB_reference_is_always_ref():
    """A parameter defaulting to a reference pressure is named ``ref``, and
    ``ref`` defaults to a reference pressure or ``None``. H1's known case:
    ``Field.sound_exposure_level(reference=REFERENCE_PRESSURE_WATER)``."""
    offenders = sorted(_reference_offenders())
    assert not offenders, offenders


# ── rule 3: one place decides a default ───────────────────────────────────

#: Writer -> the engine whose knobs it writes.
_WRITER_ENGINE = {
    'write_bellhop_env_file': 'Bellhop', 'write_kraken_env_file': 'Kraken',
    'write_scooter_env_file': 'Scooter', 'write_sparc_env_file': 'SPARC',
    'write_bounce_input_file': 'Bounce', 'write_oast_input': 'OAST',
    'write_oasn_input': 'OASN', 'write_oasp_input': 'OASP',
    'write_oasr_input': 'OASR', 'write_oass_input': 'OASS',
    'write_oassp_input': 'OASSP',
}

#: Writer parameters that restate an engine default (N1, scheduled after
#: Phase 5): each name below is a knob of the writer's engine, and the
#: writer gives it a default of its own.
_WRITER_DEFAULTS = _RATCHET.get('writer_defaults', frozenset())


#: Knobs of the host, not of the deck: a writer may default them.
_HOST_KNOBS = frozenset({'verbose'})


def _writer_defaults():
    import uacpy.io as io
    out = set()
    for writer, engine in _WRITER_ENGINE.items():
        fn = getattr(io, writer, None)
        cls = getattr(uacpy, engine)
        if fn is None:
            continue
        knobs = set(inspect.signature(cls).parameters) - _HOST_KNOBS
        for p in inspect.signature(fn).parameters.values():
            if p.name in knobs and p.default is not p.empty \
                    and p.default is not None:
                out.add(f'{writer}({p.name}={p.default!r})')
    return out


def _engine_default_constants():
    """``{name: knob}`` of :mod:`uacpy.core.engine_defaults`, read from its
    source: the knob is the name after the engine prefix."""
    tree = ast.parse((_PACKAGE / 'core' / 'engine_defaults.py')
                     .read_text(encoding='utf-8'))
    names = [n.targets[0].id for n in tree.body if isinstance(n, ast.Assign)
             and isinstance(n.targets[0], ast.Name)
             and n.targets[0].id.isupper() and n.targets[0].id != '__all__']
    return {n: n.split('_', 1)[1].lower() for n in names}


def _knob_default_offenders():
    """A knob with a named default stated as anything else: an engine
    constructor whose default is not the constant (or None), a writer
    whose default is not None or whose body never reads the constant."""
    import uacpy.io as io
    consts = _engine_default_constants()
    out = set()
    for writer, engine in _WRITER_ENGINE.items():
        prefix = engine.upper() + '_'
        mine = {k: n for n, k in consts.items() if n.startswith(prefix)}
        cls = getattr(uacpy, engine)
        init = inspect.getsource(cls.__init__)
        fn = getattr(io, writer, None)
        wsrc = inspect.getsource(fn) if fn is not None else ''
        for knob, name in mine.items():
            p = inspect.signature(cls).parameters.get(knob)
            if p is not None and p.default is not None and \
                    not re.search(rf'\b{knob}\b[^=\n]*= {name}\b', init):
                out.add(f'{engine}({knob}) states its default as a literal')
            if fn is None:
                continue
            wp = inspect.signature(fn).parameters.get(knob)
            if wp is not None and wp.default is not None:
                out.add(f'{writer}({knob}) has a default of its own')
            if wp is not None and name not in wsrc:
                out.add(f'{writer}({knob}) never reads {name}')
    return out


def test_a_knob_default_has_one_source():
    """An engine and its writer state a shared knob default once, as the
    named constant of :mod:`uacpy.core.engine_defaults`: the constructor
    defaults to it, the writer defaults to None and reads it."""
    _check(_knob_default_offenders(), (), 'knob default stated twice')


def test_no_engine_default_is_defined_twice():
    """A name of :mod:`uacpy.core.engine_defaults` is assigned nowhere
    else in the package."""
    names = set(_engine_default_constants())
    out = set()
    for rel, tree in _package_trees():
        if rel == 'core/engine_defaults.py':
            continue
        for node in tree.body:
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and target.id in names:
                        out.add(f'{rel} {target.id}')
    _check(out, (), 'engine default defined twice')


def test_a_writer_states_no_default_the_model_resolves():
    """An io writer does not decide a knob's default a second time: a writer
    parameter named as its engine's knob has no default but ``None``."""
    _check(_writer_defaults(), _WRITER_DEFAULTS, 'writer default')


#: The constants a default must be spelt as, by parameter-name pattern.
_DEFAULT_CONSTANTS = (
    (r'(^|_)(sound_speed|c0)$', 'DEFAULT_SOUND_SPEED'),
    (r'^ref$', 'REFERENCE_PRESSURE_WATER'),
    (r'(^|_)density(_z)?$', 'DEFAULT_WATER_DENSITY_G_CM3'),
)


def _literal_defaults():
    out = set()
    for rel, tree in _package_trees():
        for fn in ast.walk(tree):
            if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            a = fn.args
            pos = a.posonlyargs + a.args
            pairs = list(zip(pos[len(pos) - len(a.defaults):], a.defaults)) + \
                [(x, d) for x, d in zip(a.kwonlyargs, a.kw_defaults) if d]
            for arg, default in pairs:
                if not isinstance(default, ast.Constant) or \
                        isinstance(default.value, bool) or \
                        not isinstance(default.value, (int, float)):
                    continue
                for rx, const in _DEFAULT_CONSTANTS:
                    if re.search(rx, arg.arg) and \
                            float(default.value) == getattr(constants, const):
                        out.add(f'{rel}:{fn.lineno} {fn.name}({arg.arg}) '
                                f'-> {const}')
    return out


def test_defaults_name_their_constant():
    """A default equal to a package constant is spelt as the constant, so
    changing the package's water or reference pressure changes every
    signature at once."""
    offenders = sorted(_literal_defaults())
    assert not offenders, offenders


# ── rule 4: signature order ───────────────────────────────────────────────

#: Functions that take a sample rate but no sampled record: their
#: ``sample_rate`` is keyword-only (H3).
_NO_RECORD = (
    'uacpy.acoustic_signal.lfm_chirp', 'uacpy.acoustic_signal.hfm_chirp',
    'uacpy.acoustic_signal.tone_burst', 'uacpy.acoustic_signal.bpsk_modulate',
    'uacpy.acoustic_signal.make_bandlimited_noise',
    'uacpy.acoustic_signal.make_mseq_probe', 'uacpy.comms.janus_modulate',
    'uacpy.comms.janus_transmit', 'uacpy.comms.multipath_channel',
    'uacpy.comms.fading_taps', 'uacpy.acoustic_signal.impulse_response',
)

#: Functions that take a sampled record first: ``sample_rate`` follows it
#: positionally (H3).
_AFTER_RECORD = ('uacpy.acoustic_signal.cepstrum', 'uacpy.acoustic_signal.welch')


def _sample_rate_kind(label):
    module, name = label.rsplit('.', 1)
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        fn = getattr(importlib.import_module(module), name)
    return inspect.signature(fn).parameters['sample_rate'].kind


def test_sample_rate_follows_its_record():
    """``sample_rate`` is positional after the record it samples and
    keyword-only when there is no record. H3's known cases:
    ``lfm_chirp(f0, f1, duration, sample_rate)`` and ``cepstrum(data, *,
    sample_rate)``."""
    from inspect import Parameter
    wrong = [f'{f} (positional)' for f in _NO_RECORD
             if _sample_rate_kind(f) != Parameter.KEYWORD_ONLY]
    wrong += [f'{f} (keyword-only)' for f in _AFTER_RECORD
              if _sample_rate_kind(f) == Parameter.KEYWORD_ONLY]
    # and nowhere is it the first positional
    wrong += [label for label, p in _parameters() if p.name == 'sample_rate'
              and p.kind is Parameter.POSITIONAL_OR_KEYWORD
              and list(inspect.signature(dict(_public_callables())[label])
                       .parameters).index('sample_rate') == 0]
    assert not wrong, wrong


#: A family's core arguments, in the order every member takes them.
_FAMILIES = {
    'beamforming': ('positions_m', 'angles_deg', 'frequency', 'sound_speed'),
}

#: Members out of their family's order, still open.
_OUT_OF_ORDER = _RATCHET.get('out_of_order', frozenset())


def _out_of_order():
    out = set()
    for label, obj in _public_callables():
        sig = _signature(obj)
        if sig is None:
            continue
        names = [n for n, p in sig.parameters.items()
                 if p.kind is not p.KEYWORD_ONLY]
        for family, order in _FAMILIES.items():
            present = [n for n in order if n in names]
            if len(present) >= 2 and \
                    [n for n in names if n in present] != present:
                out.add(f'{label} ({family})')
    return out


def test_a_family_keeps_one_argument_order():
    """The core arguments of a family come in one order in every member's
    positional parameters (:data:`_FAMILIES`)."""
    _check(_out_of_order(), _OUT_OF_ORDER, 'out-of-order member')


# ── rule 5: errors ────────────────────────────────────────────────────────

_BUILTIN_USER_ERRORS = ('ValueError', 'RuntimeError', 'AssertionError')

#: Developer-facing builtin raises, kept: the output-contract check of a
#: model's own stage 5 (a package bug, not a user's input).
_BUILTIN_RAISES = frozenset()


def _builtin_raises():
    out = set()
    for rel, tree in _package_trees():
        for fn in ast.walk(tree):
            if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)) or \
                    (fn.name.startswith('__') and fn.name != '__post_init__'):
                continue
            for node in ast.walk(fn):
                if isinstance(node, ast.Raise) and isinstance(node.exc, ast.Call) \
                        and isinstance(node.exc.func, ast.Name) \
                        and node.exc.func.id in _BUILTIN_USER_ERRORS:
                    out.add(f'{rel} {fn.name} {node.exc.func.id}')
    return out


def test_user_errors_are_uacpy_errors():
    """A refusal a user can reach raises a :class:`~uacpy.UACPYError`
    subclass, so ``except uacpy.UACPYError`` catches every one. H6's known
    case: ``RunSettings.__post_init__``'s ``ValueError``."""
    _check(_builtin_raises(), _BUILTIN_RAISES, 'builtin raise')


def _message_text(node):
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        return ''.join(v.value if isinstance(v, ast.Constant) else '{}'
                       for v in node.values)
    return None


#: Error classes that build their message from structured arguments.
_COMPOSED_ERRORS = frozenset({'UnsupportedFeatureError',
                              'ExecutableNotFoundError', 'InvalidDepthError'})

#: Refusals whose message has no closing stop (N4, after Phase 5).
_UNSTOPPED = _RATCHET.get('unstopped_messages', frozenset())

#: Refusals whose last interpolation is itself a stopped sentence: a
#: producer's problem, hint or remediation text, or another uacpy
#: error's message. The literal ends mid-sentence; the message a user
#: reads ends with the stop that text carries.
_SENTENCE_TAILS = frozenset({
    'acoustic_signal/_synthesis.py require_source_waveform: ...{}: {}',
    'core/_beamforming.py snapshot_covariance: ...be a numeric array; got {}. {}',
    'core/_validate.py _nyquist_check: ...{}: {} ({} Hz) is {} {}',
    'core/_validate.py _nyquist_check: ...{}: {} {} Hz are {} {}',
    'core/_validate.py require_finite_signal: ...umpy holds as dtype=object. {}',
    'core/_validate.py require_positive_finite_scalar: ...e > 0{} and finite (got {}).{}',
    'core/_validate.py require_real_signal: ... be real (got complex input){}',
    'core/boundary.py _delegate_write: ...{}.{} = {}: {}',
    'data/wind_live.py _wind_speed: ... no wind speed at ({}, {}): {}',
    'io/bathy_io.py _boundary_rows: ..., value) rows, got shape {}.{}',
    'io/env_reader.py _vector: ...read_env: {}, {}: {}',
    'io/oases_reader.py read_oases_rhs_header: ...s smooth. Underlying error: {}',
    'models/_knobs.py refuse_unknown_knob: ... change nothing a run reads.{}',
    'models/base.py _require_timeseries_signal: ....run(run_mode=TIME_SERIES): {}',
    'models/kraken/_model.py _run_kraken_executable: ... the strongest leaky ones.\n\n{}',
    'models/oases/oasp.py _oasp_sweep: ...ompute the top of the band. {}',
    'models/ram/_band.py broadband_frequencies: ...ro or negative frequencies. {}',
    'models/ram/grid.py optimize_grid_relaxing: ...this range. Optimiser said: {}',
    'models/scooter/_plan.py refuse_too_few_wavenumbers: ...w = {} and c_high = {} m/s. {}',
})


def _refusal_message(call):
    """The node holding the message text of the error ``call`` builds:
    ``stderr=`` for a ModelExecutionError (its first argument is the
    model's name), ``None`` for an error that composes its message from
    structured arguments (:data:`_COMPOSED_ERRORS`: the feature, the
    executable, the depths), the first argument otherwise."""
    name = _name_of(call.func)
    if name in _COMPOSED_ERRORS:
        return None
    if name == 'ModelExecutionError':
        return {k.arg: k.value for k in call.keywords}.get('stderr')
    return call.args[0] if call.args else None


def _unstopped_in(rel, tree):
    """``rel function: ...tail`` for each raise in ``tree`` whose literal
    message does not end as a sentence does."""
    out = set()
    for fn in ast.walk(tree):
        if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for node in ast.walk(fn):
            if not (isinstance(node, ast.Raise)
                    and isinstance(node.exc, ast.Call)):
                continue
            message = _refusal_message(node.exc)
            text = _message_text(message) if message is not None else None
            # an interpolation is not a stop: '{got!r}.' ends one
            if text and not text.rstrip().endswith(
                    ('.', '?', ')', '"', "'", ':')):
                out.add(f'{rel} {fn.name}: ...{text.rstrip()[-30:]}')
    return out


def _unstopped_messages():
    out = set()
    for rel, tree in _package_trees():
        out |= _unstopped_in(rel, tree)
    return out


def test_the_stop_rule_reads_only_the_message_argument():
    """The rule reads the message an error is built from, never another
    argument: a composed error's feature name and a ModelExecutionError's
    model name are not messages."""
    source = (
        "def f():\n"
        "    raise UnsupportedFeatureError('OASP', 'read_oasp_trf')\n"
        "def g():\n"
        "    raise ModelExecutionError('OASSP', return_code=0,\n"
        "                              stderr='the rhs differs.')\n"
        "def h():\n"
        "    raise ModelExecutionError('OASSP', return_code=0,\n"
        "                              stderr='the rhs differs')\n"
        "def k():\n"
        "    raise ConfigurationError('no stop here')\n")
    found = _unstopped_in('m.py', ast.parse(source))
    assert found == {'m.py h: ...the rhs differs',
                     'm.py k: ...no stop here'}, found


def test_every_refusal_ends_with_a_stop():
    """A literal refusal message ends as a sentence does; a message whose last
    character is an interpolation has no stop."""
    _check(_unstopped_messages(), _UNSTOPPED | _SENTENCE_TAILS,
           'unstopped message')


# ── rule 6: numpydoc ──────────────────────────────────────────────────────

def _documented_names(doc, section='Parameters'):
    lines = doc.splitlines()
    names, inside = [], False
    for i, line in enumerate(lines):
        nxt = lines[i + 1] if i + 1 < len(lines) else ''
        if re.fullmatch(r'-{3,}', nxt.strip()) and line.strip():
            inside = line.strip() in (section, 'Other Parameters')
            continue
        if inside:
            m = re.match(r'^(\*{0,2}[A-Za-z_]\w*(?:\s*,\s*\*{0,2}[A-Za-z_]\w*)*)'
                         r'\s*(:|$)', line)
            if m:
                names += [n.strip().lstrip('*') for n in m.group(1).split(',')]
    return names


#: Callables whose Parameters section misses signature names (N2).
_UNDOCUMENTED = _RATCHET.get('undocumented', frozenset())


def _parameter_names(sig):
    """The names a Parameters section owes an entry: every parameter of
    ``sig`` but ``self`` / ``cls`` (a method reached through its class
    carries one) and the ``*args`` / ``**kwargs`` catch-alls."""
    return [n for n, p in (sig.parameters.items() if sig else ())
            if n not in ('self', 'cls')
            and p.kind not in (p.VAR_POSITIONAL, p.VAR_KEYWORD)]


def test_a_method_owes_no_entry_for_self():
    """``self``, ``cls`` and the catch-alls owe no entry; every other
    parameter does."""
    class Probe:
        def only_self(self):
            pass

        def with_args(self, a, *rest, b=1, **extra):
            pass

        @classmethod
        def build(cls, c):
            pass

    assert _parameter_names(inspect.signature(Probe.only_self)) == []
    assert _parameter_names(inspect.signature(Probe.with_args)) == ['a', 'b']
    assert _parameter_names(inspect.signature(Probe.__dict__['build']
                                              .__func__)) == ['c']


def _undocumented():
    out = set()
    for label, obj in _public_callables():
        doc = inspect.getdoc(obj) or ''
        if not re.search(r'^Parameters\n-{3,}', doc, re.M):
            continue
        sig = _signature(obj)
        if sig is None:
            continue
        documented = set(_documented_names(doc))
        missing = [n for n in _parameter_names(sig) if n not in documented]
        if missing:
            out.add(f'{label}: {", ".join(missing)}')
    return out


def test_every_documented_callable_names_its_parameters():
    """A Parameters section names every parameter of its signature."""
    _check(_undocumented(), _UNDOCUMENTED, 'undocumented parameter set')


#: Public functions with parameters and no Parameters section (N3).
_NO_PARAMETERS_SECTION = _RATCHET.get('no_parameters_section', frozenset())


def _no_parameters_section():
    out = set()
    for label, obj in _public_callables():
        if not inspect.isfunction(obj) or label.count('.') > 2 and \
                inspect.isclass(dict(_public_objects()).get(
                    label.rsplit('.', 1)[0])):
            continue
        names = _parameter_names(_signature(obj))
        if names and not re.search(r'^Parameters\n-{3,}',
                                   inspect.getdoc(obj) or '', re.M):
            out.add(label)
    return out


def test_a_public_function_with_parameters_has_a_Parameters_section():
    """A public function that takes parameters documents them in a
    numpydoc Parameters section (a ratchet: the list only shrinks)."""
    _check(_no_parameters_section(), _NO_PARAMETERS_SECTION,
           'function without a Parameters section')


# ── rule 7: the export protocol ───────────────────────────────────────────

#: Behavioural classes, which hold no record to export.
_BEHAVIOURAL = frozenset({
    'Job', 'ModelSpec', 'FRF', 'CommsReceiver', 'OFDMReceiver',
    'OFDMTransmitter', 'Transmitter', 'Modulator', 'ConvCode', 'DFE',
})

#: Record types not yet on the protocol.
_NOT_EXPORTABLE = _RATCHET.get('not_exportable', frozenset())


def _not_exportable():
    from uacpy.core._export import Exportable
    from uacpy.models.base import PropagationModel
    out = set()
    for label, obj in _public_objects():
        if not inspect.isclass(obj) or issubclass(obj, BaseException) or \
                issubclass(obj, PropagationModel) or \
                obj.__name__ in _BEHAVIOURAL or \
                any(b.__name__ == 'Enum' for b in obj.__mro__):
            continue
        if not issubclass(obj, Exportable) and not (
                hasattr(obj, 'to_dict') and hasattr(obj, 'from_dict')):
            out.add(label)
    return out


def test_every_public_record_type_is_exportable():
    """A public record type is on the export protocol (or at least saves
    and loads through ``to_dict`` / ``from_dict``)."""
    _check(_not_exportable(), _NOT_EXPORTABLE, 'record type off the protocol')


# ── decision 6: package code never reads metadata ─────────────────────────

#: Metadata reads in package code still open.
_METADATA_READS = _RATCHET.get('metadata_reads', frozenset())


def _metadata_reads():
    out = set()
    for rel, tree in _package_trees():
        for node in ast.walk(tree):
            target = None
            if isinstance(node, ast.Subscript) and \
                    isinstance(node.ctx, ast.Load) and \
                    isinstance(node.value, ast.Attribute) and \
                    node.value.attr == 'metadata' and \
                    isinstance(node.slice, ast.Constant):
                target = node.slice.value
            elif isinstance(node, ast.Call) and \
                    isinstance(node.func, ast.Attribute) and \
                    node.func.attr == 'get' and node.args and \
                    isinstance(node.args[0], ast.Constant):
                holder = node.func.value
                # ``(x.metadata or {}).get(key)`` reads metadata too
                if isinstance(holder, ast.BoolOp):
                    holder = holder.values[0]
                if isinstance(holder, ast.Attribute) and \
                        holder.attr == 'metadata':
                    target = node.args[0].value
            if target is not None:
                out.add(f'{rel}: {target}')
    return out


def test_package_code_reads_no_metadata_key():
    """Package code reads no ``metadata`` key (decision 6: metadata is
    provenance). H7's known case: ``Covariance`` read its unit from
    ``metadata['unit']``."""
    _check(_metadata_reads(), _METADATA_READS, 'metadata read')
